#testA4:
#  script:
#    - "echo ok checking submission for A4"
#    - "ls docs/url.txt"
#    - "echo check that pythonanywhere.com exists in url.txt"
#    - "if  grep -vq 'pythonanywhere.com' docs/url.txt; then echo 'pythonanywhere.com not found'; exit 1; fi"

#testA3:
#  script:
#    - "echo ok checking submission for A3"
#    - "cd src;"
#    - "echo creating database tables"
#    - "python3 manage.py makemigrations park_at_dcu"
#    - "python3 manage.py migrate"
#    - "echo checking for data_loading scripts"
#    - "ls park_at_dcu/load_historical_data.py"
#    - "ls park_at_dcu/load_campus_data.py"
#    - "echo running python django test"
#    - "python3 manage.py test park_at_dcu"
#    - "echo finished A3 submission checks"


#testA2:
#  script:
#    - "django-admin --version"
#    - "echo ok checking submission for A2"
#    - "echo running python django test"
#    - "cd src; python manage.py test park_at_dcu"
#    - "echo finished A2 submission checks"

#testA1:
#  script:
#    - "ls -l"
#    - "echo NOTE: this does not check your SQL queries are correct, just that the format can be read."
#    - "cd data"
#    - "ls A1_queries.sql"
#    - "echo check query format"
#    - "F=$(grep -e '-- Q[12345]: ' A1_queries.sql | wc -l)"
#    - "echo $F queries identified"
#    - "if [ $F -ne 5 ]; then echo 'Unable to find all 5 queries. See wiki for format requirements.'; exit 1; fi"
#    - "echo username detected: $CI_PROJECT_NAMESPACE"
#    # the username.sql file should contain all SQL needed to create the database
#    - "ls $CI_PROJECT_NAMESPACE.sql"
#    - "if grep -q -m1 -ioe 'CREATE' $CI_PROJECT_NAMESPACE.sql && grep -q -m1 -ioe 'INSERT' $CI_PROJECT_NAMESPACE.sql; then echo 'SQL appears valid'; else echo 'Error: No CREATE or INSERT statements found.'; exit 1; fi"
#    - "echo finished A1 submission checks"


#testA0:
#  script:
#    - "django-admin --version"
#    - "echo ok checking submission for A0"
#    - "ls -l"
#    - "ls docs/README.md"
#    - "cat docs/README.md"
#    - "echo running python django test"
#    - "cd src; python manage.py test park_at_dcu"
#    - "echo finished A0 submission checks"
