image: python:2

before_script:
  - pip install django

testA0:
  script:
    - "echo ok checking submission for A0"
    - "ls -l"
    - "ls docs/README.md"
    - "cat docs/README.md"
    - "echo running python django test"
    - "django-admin --version"
    - "cd src; python manage.py test park_at_dcu"
    - "echo finished A0 submission checks"
